config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'helitages#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy]

  namespace :admin do
    resources :genres
    resources :newses
    resources :helitages
    resources :countries
    
  end

  namespace :user do
    get '/companies/tops' => 'companies#top', as: 'companies_top'
    get '/companies/historys' => 'companies#history', as: 'companies_history'
    get '/companies/inquiries' => 'companies#inquiry', as: 'companies_inquiry'
    get '/companies/overviews' => 'companies#overview', as: 'companies_overview'
    resources :companies

    get '/helitages/helitages' => 'helitages#helitage', as: 'helitages_helitage'
    resources :helitages
  end


end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companey.rb
class Companey < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/helitage.rb
class Helitage < ApplicationRecord
  attachment :image
end

app/models/news.rb
class News < ApplicationRecord
  attachment :image
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  #ジャンル一覧・作成
    def index
        @genre = Genre.new
        @genres = Genre.all

    end
    
     def create
        @genre = Genre.new(genre_params)
        if @genre.save
          flash[:notice] = "登録が完了しました。"
          redirect_to admin_genres_path
        else
          @genres = Genre.all
          render:index
        end
     end
    
     #ジャンル編集
     def edit
      @genre = Genre.find(params[:id])
     end
    
     #ジャンルアップデート
     def update
      genre = Genre.find(params[:id])
      genre.update(genre_params)
      redirect_to admin_genres_path
     end
    
    #ジャンル削除
    def destroy
      @genre = Genre.find(params[:id])
      @genre.destroy
      redirect_to admin_genres_path
    end
    
    #ストロングパラメータ
     private
     def genre_params
         params.require(:genre).permit(:name)
     end

end

app/controllers/admin/helitages_controller.rb
class Admin::HelitagesController < ApplicationController
  def new
    @helitage = Helitage.new
    @genres = Genre.all
    @countries = Country.all
  end


  def create
    @helitage = Helitage.new(helitage_params)
    #投稿

    if @helitage.save
        redirect_to admin_helitages_path
    else
        @genres = Genre.all
        render :new
    end
  end

  def index
    @helitages = Helitage.all
  end

  def show
    @helitage = Helitage.find(params[:id])
  end

  def edit
    @helitage = Helitage.find(params[:id])
    @genres= Genre.all
  end

  def destroy
    @helitages = Helitage.find(params[:id])
    @helitages.destroy
    redirect_to helitages_path
  end

  def update
  @helitages = Helitage.find(params[:id])
  @helitages.update(helitage_params)
  redirect_to helitage_path(@helitages)

  end

  private
    def helitage_params
      params.require(:helitage).permit(:genre_id, :address, :latitude, :longitude, :name, :point, :body, :time, :holiday, :price, :image)
    end

end

app/controllers/admin/newses_controller.rb
class Admin::NewsesController < ApplicationController
  def new
    @news = News.new
    @genres = Genre.all
    @countries = Country.all
  end


  def create
    @news = News.new(news_params)
    #投稿

    if @news.save
        redirect_to admin_newses_path
    else
        @genres = Genre.all
        render :new
    end

  end

  def index
    @newses = News.all.order("id DESC")
    @current_time = Time.current
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
    @genres= Genre.all
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to Newss_path
  end

  def update
    @newss = News.find(params[:id])
    @newss.update(news_params)
    redirect_to news_path(@newss)

  end

  private
    def news_params
      params.require(:news).permit(:genre_id, :address, :name, :point, :body, :image)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  
end

app/controllers/helitages_controller.rb
class HelitagesController < ApplicationController
  def top
  end
end

app/controllers/user/companies_controller.rb
class User::CompaniesController < ApplicationController
end

app/controllers/user/helitages_controller.rb
class User::HelitagesController < ApplicationController
  def helitage
  end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/helitages_helper.rb
module Admin::HelitagesHelper
end

app/helpers/admin/newses_helper.rb
module Admin::NewsesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helitages_helper.rb
module HelitagesHelper
end

app/helpers/user/companies_helper.rb
module User::CompaniesHelper
end

app/helpers/user/helitages_helper.rb
module User::HelitagesHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>
<%= form_with model:@genre, url:admin_genre_path(@genre.id),local:true do |f| %>

<div class="form-group">
  <label for="name">ジャンル名</label>
  <%= f.text_field :name %>
  <%= f.submit '更新' %>
  <%= link_to "削除する", admin_genre_path(@genre), class: "btn btn-danger" , method: :delete %></td>
</div>
<% end %> 

app/views/admin/genres/index.html.erb
 <h2>ジャンル</h2>
  <%= form_with model: @genre, url:admin_genres_path, local:true do |f| %>

    <%= f.text_field :name,placeholder: "観光地、お寺..." %>
    <%= f.submit '新規登録', class: 'btn btn-success' %>
  <% end %>

   <div class="col-md-6">
    <table class="table">
     <thead>
       <tr>
        <th>ジャンル</th>
        <th></th>
       </tr>
     </thead>
      <tbody>
       <% @genres.each do |genre| %>
      　 <tr>
       　 <td>

          <%= genre.name %>
       　 </td>
       　 <td>

          <%= link_to "編集する",edit_admin_genre_path(genre), class:"btn btn-success"%>
       　 </td>
       </tr>
       <% end %>
      </tbody>
    </table>
   </div>
  </div>
</div>

app/views/admin/helitages/edit.html.erb
<h1>世界遺産編集</h1>

app/views/admin/helitages/index.html.erb
<h1>世界遺産一覧</h1>

<%= link_to "世界遺産作成",new_admin_helitage_path, class:"btn btn-success"%></br>

 <% @helitages.each do |helitage| %>
    <div class="helitage_card">
        <%= link_to admin_helitage_path(helitage) do%>
            <%= attachment_image_tag helitage, :image, :fill, 200, 200 %></br>
            <%= helitage.name %></br>
            <%= helitage.point %></br>
        <% end %>
    </div>
 <% end %>

app/views/admin/helitages/new.html.erb
<h1>世界遺産投稿</h1>

<!-- 記録作成 -->
<%= form_with model:@helitage, url:admin_helitages_path,local:true do |f| %></br>

<%= f.attachment_field :image %></br>


<%= f.label :世界遺産名%>
<%= f.text_field :name,placeholder: "白神山地" %></br>


<!--%= f.label :国名選択 %-->
<!--%= f.collection_select :country_id, Country.all, :id, :name %-->

<%= f.label :ジャンル%>
<%= f.collection_select(:genre_id, @genres, :id, :name, include_blank: "ジャンルは？",size: "20x20") %></br>

<%= f.label :見出し%>
<%= f.text_field :point %></br>

<%= f.label :感想%></br>
<%= f.text_area :body,size: "100x10" %></br>


<%= f.label :予算%>
<%= f.text_field :price %></br>

<%= f.label :住所%>
<%= f.text_field :address %></br>

<%= f.label :営業時間%>
<%= f.text_field :time %></br>

<%= f.label :営業時間%>
<%= f.text_field :holiday %></br>

<%= f.submit '投稿' %>


<% end %>

app/views/admin/helitages/show.html.erb
<h1>世界遺産詳細</h1>

<%= attachment_image_tag @helitage, :image, :fill, 400, 400 %></br>

<table>
      <h2><%= @helitage.name %></h2>


<!--                    <tr>-->
<!--                        <th>都道府県</th>-->
<!--                        <td>%= @record.prefecture.name %></td>-->
<!--                    </tr>-->
  <thead>
    <tr>
      <!--<td><!%= @helitage.genre_id.name %></td>-->
    </tr>
  </thead>

  <thead>
    <tr>
      <th></th>
      <td></td><%= @helitage.point %></td>
    </tr>
  </thead>
  <thead>
    <tr>
        <td><%= @helitage.body %></td>
    </tr>
  <thead>
    <tr>
      <th>Info</th>
    </tr>
    <tr>
      <td>住所:<%= @helitage.address %></td>
    </tr>
    <tr>
      <td>営業時間:<%= @helitage.time %></td>
    </tr>
    <tr>
      <td>定休日:<%= @helitage.holiday %></td>
    </tr>
    <tr>
      <td>予算:<%= @helitage.price%></td>
    </tr>
    <tr>
      <!--<td>URL:<!%= @helitage.url%></td>-->
    </tr>
  </thead>
</table>
</div>
  <%= link_to "編集する", edit_admin_helitage_path(@helitage), class: "btn btn-danger" %>
</div>

app/views/helitages/top.html.erb
<div class="top_image">
    <p class="top_text">
      Let's go see the wonderful scenery and culture that we haven't seen yet.
    </p>
    </p>
  </div>
</div>

<div class="top_main">
  <h2>NEWS</h2>
  
  
</div>

app/views/user/companies/history.html.erb
<h1>企業のあゆみ</h1>
<dl>
    <dt>19××年11月</dt>
    <dd>
        <h2>会社設立</h2>
        <p>会社について</p>
    </dd>
    <dt>19××年4月</dt>
    <dd>
        <h2>観光事業に力を入れる。</h2>
        <p>旅行事業活性化に努める</p>
    </dd>
    <dt>20××年4月</dt>
    <dd>
        <h2>世界遺産ホームページ立ち上げ</h2>
        <p>世界遺産についておおくの方々に知ってもらい、歴史・伝統について知ってもらう</p>
    </dd>
    <dt>20××年4月</dt>
    <dd>
        <h2>子会社〇〇を設立</h2>
        <p></p>
    </dd><dt>2008年4月</dt>
    <dd>
</dl>

app/views/user/companies/inquiry.html.erb
<h1>問い合わせ</h1>

app/views/user/companies/overview.html.erb
<h1>企業方針</h1>

app/views/user/companies/top.html.erb
<h1>会社概要</h1>

<h2>日本の良さを多くの方に</h2>

<h2>事業内容</h2>
<p>日本の良さを世界に広める為のサイトを作成しました。</p>




<h2>CONTENTS</h2>
 <%= link_to "企業のあゆみ", user_companies_history_path %>
 <%= link_to "企業方針", user_companies_overview_path %>
 <%= link_to "問い合わせ", user_companies_inquiry_path %>

app/views/user/helitages/helitage.html.erb
<h2>世界遺産とは</h2>
<p>
    世界遺産とは、地球の生成と人類の歴史によって生み出され、過去から現在へと引き継がれてきたかけがえのない宝物です。</li>
    現在を生きる世界中の人びとが過去から引継ぎ、未来へと伝えていかなければならない人類共通の遺産です。</li>

    1972年の第17回UNESCO総会で採択された世界遺産条約（正式には『世界の文化遺産及び自然遺産の保護に関する条約』）の中で定義されています。</li>
    世界遺産は1092件（文化遺産845件、自然遺産209件、複合遺産38件）、条約締約国は193カ国(2018年12月 調べ)です。</li>
</p>

<div class="helitage_kind">
    <div id="sec">
      <ul>
        <li>
          <span class="fa fa-code"></span>
          <p class="title01">文化遺産</p>
          <p>顕著な普遍的価値を有する、記念物、建造物群、遺跡、文化的景観など。</p>
        </li>

        <li>
          <span class="fa fa-code"></span>
          <p class="title01">自然遺産</p>
          <p>顕著な普遍的価値を有する、地形や地質、生態系、絶滅のおそれのある動植物の生息・生育地など</p>
        </li>
        <li>
          <span class="fa fa-code"></span>

          <p class="title01">複合遺産</p>
          <p>文化遺産と自然遺産の両方の価値を兼ね備えているもの</p>
        </li>
      </ul>
    </div>
</div>

<ul class="sample1">
    <h2>世界遺産の登録基準</h2>
        <ul>
            <li>(i)人間の創造的才能を表す傑作である。
            <li>(ii)建築、科学技術、記念碑、都市計画、景観設計の発展に重要な影響を与えた、ある期間にわたる価値観の交流又はある文化圏内での価値観の交流を示すものである。</li>
            <li>(iii)現存するか消滅しているかにかかわらず、ある文化的伝統又は文明の存在を伝承する物証として無二の存在(少なくとも希有な存在)である。</li>
            <li>(iv)歴史上の重要な段階を物語る建築物、その集合体、科学技術の集合体、あるいは景観を代表する顕著な見本である。</li>
            <li>(v)あるひとつの文化(または複数の文化)を特徴づけるような伝統的居住形態若しくは陸上・海上の土地利用形態を代表する顕著な見本である。又は、人類と環境とのふれあいを代表する顕著な見本である(特に不可逆的な変化によりその存続が危ぶまれているもの)</li>
            <li>(vi)顕著な普遍的価値を有する出来事(行事)、生きた伝統、思想、信仰、芸術的作品、あるいは文学的作品と直接または実質的関連がある(この基準は他の基準とあわせて用いられることが望ましい)。</li>
            <li>(vii)最上級の自然現象、又は、類まれな自然美・美的価値を有する地域を包含する。</li>
            <li>(viii)進化の記録や、地形形成における重要な進行中の地質学的過程、あるいは重要な地形学的又は自然地理学的特徴といった、地球の歴史の主要な段階を代表する顕著な見本である。</li>
            <li>(ix)陸上・淡水域・沿岸・海洋の生態系や動植物群集の進化、発展において、重要な進行中の生態学的過程又は生物学的過程を代表する顕著な見本である。</li>
            <li>(x)学術上又は保全上顕著な普遍的価値を有する絶滅のおそれのある種の生息地など、生物多様性の生息域内保全にとって最も重要な自然の生息地を包含する。</li>
        </ul>
    </h2>

app/views/user/helitages/index.html.erb
index