config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'helitages#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy]

  namespace :admin do
    resources :genres
    resources :newses
    resources :helitages
    resources :countries
    
  end

  namespace :user do
    get '/companies/tops' => 'companies#top', as: 'companies_top'
    get '/companies/historys' => 'companies#history', as: 'companies_history'
    get '/companies/inquiries' => 'companies#inquiry', as: 'companies_inquiry'
    get '/companies/overviews' => 'companies#overview', as: 'companies_overview'
    resources :companies

    get '/helitages/helitages' => 'helitages#helitage', as: 'helitages_helitage'
    resources :helitages
  end


end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companey.rb
class Companey < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/helitage.rb
class Helitage < ApplicationRecord
  attachment :image
end

app/models/news.rb
class News < ApplicationRecord
  attachment :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  #ジャンル一覧・作成
    def index
        @genre = Genre.new
        @genres = Genre.all

    end
    
     def create
        @genre = Genre.new(genre_params)
        if @genre.save
          flash[:notice] = "登録が完了しました。"
          redirect_to admin_genres_path
        else
          @genres = Genre.all
          render:index
        end
     end
    
     #ジャンル編集
     def edit
      @genre = Genre.find(params[:id])
     end
    
     #ジャンルアップデート
     def update
      genre = Genre.find(params[:id])
      genre.update(genre_params)
      redirect_to admin_genres_path
     end
    
    #ジャンル削除
    def destroy
      @genre = Genre.find(params[:id])
      @genre.destroy
      redirect_to admin_genres_path
    end
    
    #ストロングパラメータ
     private
     def genre_params
         params.require(:genre).permit(:name)
     end

end

app/controllers/admin/newses_controller.rb
class Admin::NewsesController < ApplicationController
  def new
    @news = News.new
    @genres = Genre.all
    @countries = Country.all
  end


  def create
    @news = News.new(news_params)
    #投稿

    if @news.save
        redirect_to admin_newses_path
    else
        @genres = Genre.all
        render :new
    end

  end

  def index
    @newses = News.all.order("id DESC")
    @current_time = Time.current
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
    @genres= Genre.all
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to Newss_path
  end

  def update
    @newss = News.find(params[:id])
    @newss.update(news_params)
    redirect_to news_path(@newss)

  end

  private
    def news_params
      params.require(:news).permit(:genre_id, :address, :name, :point, :body, :image)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  
end

app/controllers/helitages_controller.rb
class HelitagesController < ApplicationController
  def top
  end
end

app/controllers/user/companies_controller.rb
class User::CompaniesController < ApplicationController
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/helitages_helper.rb
module Admin::HelitagesHelper
end

app/helpers/admin/newses_helper.rb
module Admin::NewsesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helitages_helper.rb
module HelitagesHelper
end

app/helpers/user/companies_helper.rb
module User::CompaniesHelper
end

app/helpers/user/helitages_helper.rb
module User::HelitagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelitageHomepage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="UTF-8" />
    <!-- FontAwesomeの読み込み -->
    <script src="https://kit.fontawesome.com/e9525941b3.js" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS読み込み -->
    <link rel="stylesheet" href="style.css" />
  </head>

  <body>
    <header>
    <!--ナビゲーションバー-->
      <div class='navgation'>
        <nav>
          <% if admin_signed_in? %>
            <div class="navitem">
              <%= link_to "Home", root_path %>
              <%= link_to "NEWS作成", new_admin_newse_path %>
              <%= link_to "ジャンル作成", admin_genres_path %>
              <%= link_to "世界遺産作成", new_admin_helitage_path %>
              <%= link_to "世界遺産", admin_helitages_path %>
              <%= link_to "問い合わせ一覧", user_companies_inquiry_path %>
            
          <% else %>
            <div class="navitem">
              <%= link_to "Home", root_path %>
              <%= link_to "世界遺産とは", user_helitages_helitage_path %>
              <%= link_to "企業概要", user_companies_top_path %>
              <%= link_to "問い合わせ", user_companies_inquiry_path %>
          <% end %>
          </div>
        </nav>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>
    <footer>
    <p>株式会社WTS</p>
    <!--ツイッター、インスタアイコン、フェイスブック-->
    <i class="fab fa-instagram-square fa-fw fa-2x"></i>
    <i class="fab fa-twitter-square fa-fw fa-2x"></i>
    <i class="fab fa-facebook-square fa-fw fa-2x"></i>
  </footer>
  </body>

</html>